l_japanese:
 pm_privately_owned_building_subsistence:0 "地主所有"
 pm_skyscraper_bureaucratic_nexus:0 "官僚制結合"
 pm_steam_trains:0 "蒸気機関車"
 pm_electric_trains:0 "電気機関車"
 pm_diesel_trains:0 "ディーゼル機関車"
 pm_government_run_general_industry:0 "国営"
 pm_privately_owned_general_industry:0 "個人所有"