l_japanese:
 pmg_secondary_building_rye_farm:0 "果樹園"
 pmg_secondary_building_wheat_farm:0 "果樹園"
 pmg_secondary_building_rice_farm:0 "果樹園"
 pmg_secondary_building_maize_farm:0 "果樹園"
 pmg_secondary_building_millet_farm:0 "果樹園"
 pm_no_secondary:0 "果樹園なし"