l_english:
  pm_government_run_general_industry: "Government Run"
  pm_privately_owned_general_industry: "Privately Owned"
  pm_privately_owned_building_subsistence: "Landlord Ownership"
  pm_skyscraper_bureaucratic_nexus: "Bureaucratic Nexus"
  pm_steam_trains: "Steam Trains"
  pm_electric_trains: "Electric Trains"
  pm_diesel_trains: "Diesel Trains"
