l_english:
  pmg_secondary_building_rye_farm: "Orchards"
  pmg_secondary_building_wheat_farm: "Orchards"
  pmg_secondary_building_rice_farm: "Orchards"
  pmg_secondary_building_maize_farm: "Orchards"
  pmg_secondary_building_millet_farm: "Orchards"
  pm_no_secondary: "No Orchards"